name: Lint

on: [push, pull_request]

env:
  NODE_VERSION: 16

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
              run: |
                if [ -e yarn.lock ]; then
                yarn install --frozen-lockfile
                elif [ -e package-lock.json ]; then
                npm ci
                else
                npm i
                fi

      - name: Code Linting
        run: npm run lint
